---

- name: 4.2.1.3 Ensure rsyslog default file permissions configured
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '^$FileCreateMode'
    line: '$FileCreateMode 0640'
    owner: root
    group: root
    mode: 0644

- name: 4.2.4 Ensure permissions on all logfiles are configured
  shell: "find /var/log -type f -exec chmod g-wx,o-rwx {} +"

