---

# Playbook name: test_sudo.yml
# Author:        Walter G. da Cruz
# Version:       0.1
# Date:          2019.02.07
# Description:
# Reboot host(s)
#
# The Playbook should run in a small set of host, and "should be" the same for SL, RedHat,
# or CentOS.  The same should apply for version 5.x, 6.x, or 7.x
#
# Requirements:
##############################################################################################

- hosts: all
  become: yes
  become_method: sudo
  # remote_user: walter

  tasks:
  # The shell line below should be under double quotes
  - name: Test SUDO access
    shell: "ls -al /root/"
