---

# Gather facts about all VPCs

- name: 2.2.1.0.a Install epel key for CentOS 5
  shell: "rpm --import https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-5"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '5'"

- name: 2.2.1.0.b Install epel key for CentOS 6
  shell: "rpm --import https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-6"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: 2.2.1.0.b Install epel key for CentOS 7
  shell: "rpm --import https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: 2.2.1.0 Install epel
  yum:
    name: epel-release.noarch
    state: present

- name: 2.2.1.1 Ensure time synchronization is in use
  yum:
    name: chrony.x86_64
    state: present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version != '6'"

- name: 2.2.1.2a Ensure ntp is configured
  lineinfile:
    path: "/etc/ntp.conf"
    line: "^restrict default"
    state: absent

- name: 2.2.1.2b Ensure ntp is configured
  lineinfile:
    path: "/etc/ntp.conf"
    line: "restrict -6 default kod nomodify notrap nopeer noquery"
    insertafter: "restrict default nomodify notrap noquery"

- name: 2.2.1.2c Ensure ntp is configured
  lineinfile:
    path: "/etc/ntp.conf"
    line: "restrict -4 default kod nomodify notrap nopeer noquery"
    insertafter: "restrict default nomodify notrap noquery"

- name: 2.2.1.2c Ensure ntp is configured
  lineinfile: 
    dest: "/etc/sysconfig/ntpd"
    regexp: '^OPTIONS="-g"'
    line: 'OPTIONS="-u ntp:ntp"'
    backrefs: yes

- name: 2.2.1.3 Ensure chrony is configured
  lineinfile:
    dest: "/etc/sysconfig/chronyd"
    regexp: '^OPTIONS'
    line: 'OPTIONS="-u chrony"'
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version != '6'"

# We should not remove it on QA Env
- name: 2.2.2 Ensure X Window System is not installed on CentOS 5
  # command: "yum erase xorg-x11*"
  command: "yum list xorg-x11*"
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '5'"

- name: 2.2.2 Ensure X Window System is not installed
  yum:
    name: xorg-x11*
    state: absent
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version > '5'"

