---

# Gather facts about all VPCs
- name: 6.1.3 Ensure permissions on /etc/shadow are configured
  file:
    path: "/etc/shadow"
    state: touch
    mode: 0000
    owner: root
    group: root

- name: 6.1.5 Ensure permissions on /etc/gshadow are configured
  file:
    path: "/etc/gshadow"
    state: touch
    mode: 0000
    owner: root
    group: root

- name: 6.1.7 Ensure permissions on /etc/shadow- are configured
  file:
    path: "/etc/shadow-"
    state: touch
    mode: 0000
    owner: root
    group: root

- name: 6.1.9 Ensure permissions on /etc/gshadow- are configured
  file:
    path: "/etc/gshadow-"
    state: touch
    mode: 0000
    owner: root
    group: root

- name: 6.2.8a Ensure users home directories permissions are 750 or more restrictive
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    force: true
    owner: root
    group: root
  with_fileglob:
    - "/home/*"

